- menu_name: ""


- name: "Контакт"
  url: "/contact/"
  title: "Контакт"

- name: "Impressum"
  url: "/impressum/"
  title: "Imressum"

- name: "Декларация за поверителност"
  url: "/Datenschutzerklaerung/"
  title: "Декларация за поверителност"

